M48
; DRILL file {KiCad 7.0.6} date Mon Dec 18 16:30:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-18T16:30:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X141.986Y-67.31
X141.986Y-74.676
T2
X148.844Y-76.2
X151.384Y-76.2
T0
M30
